-- Add game mechanics to horses table
ALTER TABLE horses ADD COLUMN speed INTEGER NOT NULL DEFAULT 50;
ALTER TABLE horses ADD COLUMN stamina INTEGER NOT NULL DEFAULT 50;
ALTER TABLE horses ADD COLUMN power INTEGER NOT NULL DEFAULT 50;
ALTER TABLE horses ADD COLUMN guts INTEGER NOT NULL DEFAULT 50;
ALTER TABLE horses ADD COLUMN intelligence INTEGER NOT NULL DEFAULT 50;
ALTER TABLE horses ADD COLUMN sire_id UUID REFERENCES horses(id);
ALTER TABLE horses ADD COLUMN dam_id UUID REFERENCES horses(id);
ALTER TABLE horses ADD COLUMN level INTEGER NOT NULL DEFAULT 1;
ALTER TABLE horses ADD COLUMN experience INTEGER NOT NULL DEFAULT 0;
ALTER TABLE horses ADD COLUMN training_points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE horses ADD COLUMN races_won INTEGER NOT NULL DEFAULT 0;
ALTER TABLE horses ADD COLUMN races_run INTEGER NOT NULL DEFAULT 0;
ALTER TABLE horses ADD COLUMN total_earnings INTEGER NOT NULL DEFAULT 0;

-- Add game mechanics to races table
ALTER TABLE races ADD COLUMN base_prize INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE races ADD COLUMN min_level INTEGER NOT NULL DEFAULT 1;
ALTER TABLE races ADD COLUMN max_level INTEGER NOT NULL DEFAULT 10;
ALTER TABLE races ADD COLUMN max_participants INTEGER NOT NULL DEFAULT 8;
ALTER TABLE races ADD COLUMN race_type VARCHAR(32) NOT NULL DEFAULT 'NORMAL';
ALTER TABLE races ADD COLUMN distance INTEGER NOT NULL DEFAULT 1200;
ALTER TABLE races ADD COLUMN track_condition VARCHAR(32) NOT NULL DEFAULT 'GOOD';
ALTER TABLE races ADD COLUMN is_completed BOOLEAN NOT NULL DEFAULT FALSE;

-- Create race_results table
CREATE TABLE IF NOT EXISTS race_results (
    id UUID PRIMARY KEY,
    race_id UUID NOT NULL REFERENCES races(id),
    horse_id UUID NOT NULL REFERENCES horses(id),
    position INTEGER NOT NULL,
    earnings INTEGER NOT NULL,
    race_time DECIMAL(10,2) NOT NULL,
    performance_score DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
