server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

spring:
  application:
    name: umamusume-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/umamusume}
    username: ${SPRING_DATASOURCE_USERNAME:umamusume}
    password: ${SPRING_DATASOURCE_PASSWORD:umamusume}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


